### ISSUE TITLE
where could I get the pretrained model " 'configs/config_models/epoch_60_512_ckpt.pth.tar'" ?

### ISSUE THREAD

**Issue by lizijianlove** [AlessandroRuzzi/GazeNeRF#10]
Hello, thank you to share sush an excellent work!
When I try to evalute with columbia dataset, I met a error "FileNotFoundError: [Errno 2] No such file or directory: 'configs/config_models/epoch_60_512_ckpt.pth.tar'", I can't find any clues about this error, would you give me some advices?
Thank you again!

**Comment by hengfei-wang** [comment]
Yeah, I cannot find the pre-trained model either.

**Comment by X-Shi** [comment]
Thank you for your comments. [Here](https://drive.google.com/file/d/1H7nDt8yH42_ELbS2uzkBYX-QRFgwBKQN/view?usp=sharing) is the link to the model.
