### ISSUE TITLE
Question about within-dataset evaluation

### ISSUE THREAD

**Issue by Love0n** [AlessandroRuzzi/GazeNeRF#12]
Hi @X-Shi, thank you for your great work!
I have a question about the result of within-dataset evaluation.

From 4. Experiments Table 2, the gaze and head redirection errors of STED trained on GazeCapture are much higher than those in the original paper.

Do you have any ideas about the difference between these results? Could you provide more details for your reimplementation of STED?

I would appreciate your feedback.

**Comment by X-Shi** [comment]
Hi, thank you for your interest in our work.

In our paper, GazeNeRF is only trained on ETH-XGaze dataset. In table 2, the results are cross-dataset evaluation, which means the STED is also only trained on the same subset of ETH-XGaze as GazeNeRF. In STED, they trained their model on the GazeCapture training set. This is the main reason causing their number much smaller than ours.

As for the reimplementation details of STED, AlessandroRuzzi has another repository, please check that.
