### ISSUE TITLE
Preprocessing not generating h5 file

### ISSUE THREAD

**Issue by arpit2412** [AlessandroRuzzi/GazeNeRF#5]
python dataset_pre_processing.py --dataset_dir=./columbia/0P --output_dir=./output

this is not creating h5 file? any leads

**Comment by arpit2412** [comment]
found the error for face_alignment, changed to self.fa_func = face_alignment.FaceAlignment(
            face_alignment.LandmarksType.TWO_D, flip_input=False, device=self.device
        )
       now its working

**Comment by A7med01** [comment]
I face same problem as you but still didn't work i have a new error:  about this model "**configs/config_models/model.pkl**" where did you get it ?

after getting it from another repo headnerf i have got this error :


`(gaze_nerf_env) zaitoon@GazeNeRF$ python3 dataset_pre_processing.py --dataset_dir=dataset/MPIIFaceGaze --dataset_name="mpii_face" --output_dir="dataset/output"
Overwrite the file  dataset/output/mpii_subject0001.h5
output file save to  dataset/output/mpii_subject0001.h5
Generate facial landmarks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:12<00:00,  5.08it/s]
Traceback (most recent call last):
  File "dataset_pre_processing.py", line 1490, in <module>
    dataset_processing(
  File "dataset_pre_processing.py", line 1391, in dataset_processing
    mpii_face_gaze_dataset_iteration_full(
  File "dataset_pre_processing.py", line 571, in mpii_face_gaze_dataset_iteration_full
    ) = main_process(
  File "/data/workspaces/Zaitoon_workspace/GazeNeRF/pre_processing/data_process.py", line 42, in main_process
    tt = GenMask(gpu_id=gpu_id, log=log)
  File "/data/workspaces/Zaitoon_workspace/GazeNeRF/pre_processing/gen_all_masks.py", line 32, in __init__
    self.init_model()
  File "/data/workspaces/Zaitoon_workspace/GazeNeRF/pre_processing/gen_all_masks.py", line 48, in init_model
    second_net.load_state_dict(
  File "/data/workspaces/Zaitoon_workspace/GazeNeRF/gaze_nerf_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for unet:
        Missing key(s) in state_dict: "conv1.conv1.0.weight", "conv1.conv1.0.bias", "conv1.conv1.1.weight", "conv1.conv1.1.bias", "conv1.conv1.1.running_mean", "conv1.conv1.1.running_var", "conv1.conv2.0.weight", "conv1.conv2.0.bias", "conv1.conv2.1.weight", "conv1.conv2.1.bias", "conv1.conv2.1.running_mean", "conv1.conv2.1.running_var", "conv2.conv1.0.weight", "conv2.conv1.0.bias", "conv2.conv1.1.weight", "conv2.conv1.1.bias", "conv2.conv1.1.running_mean", "conv2.conv1.1.running_var", "conv2.conv2.0.weight", "conv2.conv2.0.bias", "conv2.conv2.1.weight", "conv2.conv2.1.bias", "conv2.conv2.1.running_mean", "conv2.conv2.1.running_var", "conv3.conv1.0.weight", "conv3.conv1.0.bias", "conv3.conv1.1.weight", "conv3.conv1.1.bias", "conv3.conv1.1.running_mean", "conv3.conv1.1.running_var", "conv3.conv2.0.weight", "conv3.conv2.0.bias", "conv3.conv2.1.weight", "conv3.conv2.1.bias", "conv3.conv2.1.running_mean", "conv3.conv2.1.running_var", "conv4.conv1.0.weight", "conv4.conv1.0.bias", "conv4.conv1.1.weight", "conv4.conv1.1.bias", "conv4.conv1.1.running_mean", "conv4.conv1.1.running_var", "conv4.conv2.0.weight", "conv4.conv2.0.bias", "conv4.conv2.1.weight", "conv4.conv2.1.bias", "conv4.conv2.1.running_mean", "conv4.conv2.1.running_var", "center.conv1.0.weight", "center.conv1.0.bias", "center.conv1.1.weight", "center.conv1.1.bias", "center.conv1.1.running_mean", "center.conv1.1.running_var", "center.conv2.0.weight", "center.conv2.0.bias", "center.conv2.1.weight", "center.conv2.1.bias", "center.conv2.1.running_mean", "center.conv2.1.running_var", "up_concat4.conv.conv1.0.weight", "up_concat4.conv.conv1.0.bias", "up_concat4.conv.conv1.1.weight", "up_concat4.conv.conv1.1.bias", "up_concat4.conv.conv1.1.running_mean", "up_concat4.conv.conv1.1.running_var", "up_concat4.conv.conv2.0.weight", "up_concat4.conv.conv2.0.bias", "up_concat4.conv.conv2.1.weight", "up_concat4.conv.conv2.1.bias", "up_concat4.conv.conv2.1.running_mean", "up_concat4.conv.conv2.1.running_var", "up_concat4.up.weight", "up_concat4.up.bias", "up_concat3.conv.conv1.0.weight", "up_concat3.conv.conv1.0.bias", "up_concat3.conv.conv1.1.weight", "up_concat3.conv.conv1.1.bias", "up_concat3.conv.conv1.1.running_mean", "up_concat3.conv.conv1.1.running_var", "up_concat3.conv.conv2.0.weight", "up_concat3.conv.conv2.0.bias", "up_concat3.conv.conv2.1.weight", "up_concat3.conv.conv2.1.bias", "up_concat3.conv.conv2.1.running_mean", "up_concat3.conv.conv2.1.running_var", "up_concat3.up.weight", "up_concat3.up.bias", "up_concat2.conv.conv1.0.weight", "up_concat2.conv.conv1.0.bias", "up_concat2.conv.conv1.1.weight", "up_concat2.conv.conv1.1.bias", "up_concat2.conv.conv1.1.running_mean", "up_concat2.conv.conv1.1.running_var", "up_concat2.conv.conv2.0.weight", "up_concat2.conv.conv2.0.bias", "up_concat2.conv.conv2.1.weight", "up_concat2.conv.conv2.1.bias", "up_concat2.conv.conv2.1.running_mean", "up_concat2.conv.conv2.1.running_var", "up_concat2.up.weight", "up_concat2.up.bias", "up_concat1.conv.conv1.0.weight", "up_concat1.conv.conv1.0.bias", "up_concat1.conv.conv1.1.weight", "up_concat1.conv.conv1.1.bias", "up_concat1.conv.conv1.1.running_mean", "up_concat1.conv.conv1.1.running_var", "up_concat1.conv.conv2.0.weight", "up_concat1.conv.conv2.0.bias", "up_concat1.conv.conv2.1.weight", "up_concat1.conv.conv2.1.bias", "up_concat1.conv.conv2.1.running_mean", "up_concat1.conv.conv2.1.running_var", "up_concat1.up.weight", "up_concat1.up.bias", "final.weight", "final.bias". 
        Unexpected key(s) in state_dict: "tris", "decoder_3dmm.mu", "decoder_3dmm.b", "decoder_3dmm.sig_id", "decoder_3dmm.sig_exp", "decoder_3dmm.mu_tex", "decoder_3dmm.b_tex", "decoder_3dmm.sig_tex", "decoder_nl3dmm_new.geo_fc2.weight", "decoder_nl3dmm_new.geo_fc2.bias", "decoder_nl3dmm_new.geo_fc3.weight", "decoder_nl3dmm_new.geo_fc3.bias".`
