### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by atgao** [AlessandroRuzzi/GazeNeRF#8]
Hi! Thank you so much for sharing the code and great work. 

I'm a little bit confused on the data preprocessing steps for the ETHX-Gaze dataset. In https://github.com/AlessandroRuzzi/GazeNeRF/blob/main/pre_processing/gen_all_masks.py#L30 which model is this second model? I know the data preprocessing is partially based on the HeadNeRF repository but I'm uncertain which if the models this is referring to from here 

![image](https://github.com/AlessandroRuzzi/GazeNeRF/assets/15146761/1ea160a2-511b-4145-85f8-e3176b52d4bb)

**Comment by NYCXI** [comment]
Have you solve it? I am facing the same problem

**Comment by X-Shi** [comment]
Thank you for your comments. [Here](https://drive.google.com/file/d/1R7SQFEQYY3SLci7ByMv2snqS-HQeEBlm/view?usp=sharing) is the link to that model checkpoints.
